# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will download a prebuilt Ruby version, install dependencies and run tests with Rake
# For more information see: https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby

name: Ruby

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency: 
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

env:
  APPMAP: true
  APPLAND_API_KEY: "${{secrets.APPLAND_API_KEY}}"
  GH_TOKEN: "${{secrets.GH_TOKEN}}"

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        token: ${{ secrets.GH_TOKEN }}
    - name: Set up Ruby
    # To automatically get bug fixes and new Ruby versions for ruby/setup-ruby,
    # change this to (see https://github.com/ruby/setup-ruby#versioning):
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - name: Run tests
      run: bundle exec rake test
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ./tmp/coverage/coverage.xml
        fail_ci_if_error: true
    - name: AppMap Analysis
      run: npx @appland/scanner ci -C ${{github.event.pull_request.head.sha}} -b ${{github.event.pull_request.head.ref}} --no-upload
      if: ${{ github.ref != 'refs/heads/main' }}
    - name: AppMap Analysis
      run: npx @appland/scanner ci -C $(git rev-parse HEAD) -b $(git branch --show-current) --no-upload
      if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    - name: Simplecov Report
      uses: aki77/simplecov-report-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        failedThreshold: 10
        resultPath: tmp/coverage/.last_run.json
    - name: Archive coverage artifacts
      run: |
        if [ $? -eq 1 ]; then
        uses: actions/upload-artifact@v2
        with:
          name: coverage
          path: tmp/coverage
        fi
    - uses: 5monkeys/cobertura-action@master
      with:
        path: tmp/coverage/coverage.xml
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        minimum_coverage: 30
        show_missing: true
        show_class_names: true
        link_missing_lines: true
        report_name: code coverage results
